load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "config",
    srcs = [
        "bazel_args_splitter.go",
        "config.go",
    ],
    importpath = "bazel-compdb/internal/config",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_alecthomas_kong//:kong",
        "@in_gopkg_yaml_v3//:go_default_library",
    ],
)

go_test(
    name = "config_test",
    srcs = [
        "bazel_args_splitter_test.go",
        "config_test.go",
    ],
    embed = [":config"],
)
