load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_python//python:defs.bzl", "py_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "hello_world",
    srcs = ["hello_world.cc"],
)

py_binary(
    name = "compare_compdb",
    srcs = ["compare_compdb.py"],
    main = "compare_compdb.py",
)
