module(
    name = "bazel_compdb_example_project",
    version = "0.0.0",
)

bazel_dep(name = "bazel-compdb", version = "0.0.0")
bazel_dep(name = "rules_cc", version = "0.2.17")
bazel_dep(name = "rules_python", version = "1.7.0")

local_path_override(
    module_name = "bazel-compdb",
    path = "../..",
)
