name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@0.16.0
        with:
          bazelisk-cache: true
      - name: Run format check
        run: bazel run //tools:format.check
        shell: bash
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@0.16.0
        with:
          bazelisk-cache: true
      - name: Run tests
        run: bazel test //...
        shell: bash
  example_project:
    name: Example project compdb validation
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
        bazel: ["7.x", "8.x", "9.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: bazel-contrib/setup-bazel@0.16.0
        with:
          bazelisk-cache: true
      - name: Run bazel-compdb and validate compile_commands
        shell: bash
        working-directory: tests/integration
        run: |
          rm -f compile_commands.json
          bazel run @bazel-compdb
          bazel run //:compare_compdb
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazel }}
